let steps = [
	"<br><b>Raven Door</b>",
	"Open west-southern door (<span class='safe'>safe room</span>).",
	"Open north, west doors.",
	"Take the <span class='key'>Raven key</span> and <span class='item'>Clock hands</span>.",
	"Return to the safe room: east, south doors.",
	"Use the <span class='item'>Clock hands</span> on the grandfather clock for an <span class='item'>Eye gem</span>.",
	"Search the chest to get <span class='item'>Mystery meat</span>.",
	"Return to the lobby: east door.",
	"Unlock east door with the <span class='key'>Raven key</span>.",
	
	"<br><b>Statue puzzle</b>",
	"After the cutscene: open south, east doors.",
	"Sort the pile of books for the second and third <span class='item'>Eye gems</span>.",
	"Return to the hallway: west, north doors.",
	"Open east, north, south-middle doors.",
	"Solve the statue puzzle:",
	"<span class='indent'>Push the west statue.</span>",
	"<span class='indent'>Walk two steps south, push the east statue.</span>",
	"<span class='indent'>Walk one step south, push the west statue.</span>",
	"<span class='indent'>Push the south-westmost statue.</span>",
	"<span class='indent'>Walk one step north-east, push east statue.</span>",
	"<span class='indent'>Push the south statue.</span>",
	"<span class='indent'>Push the west statue.</span>",
	"Take the fourth <span class='item'>Eye gem</span> from the table. Leave.</span>",
	
	"<br><b>Spider door</b>",
	"Ascend the stairs.",
	"Open east door.",
	"After the cutscene: open east, west-southern doors.",
	"Search Ingram's notes for the <span class='key'>Spider key</span> and <span class='item'>Scroll fragment</span>. Leave.",
	"Return to the top of the stairs: west-northern, west doors.",
	"Unbolt then open south door to get to the upstairs lobby.",
	"Unlock west door with the <span class='key'>Spider key</span>",
	
	"<br><b>Statue door</b>",
	"Open south door.",
	"Search the dead servant for the fifth <span class='item'>Eye gem</span>.",
	"Open west door. Draw back curtain, search servant for <span class='key'>Statue key</span>.",
	"Return to the hallway: east, north doors.",
	"Open north, east doors.",
	"Unlock south-western door with the <span class='key'>Statue key</span>.",
	
	"<br><b>Scythe door</b>",
	"Take the sixth <span class='item'>Eye gem</span>.",
	"Investigate the statue twice; open west door.",
	"Investigate the statue twice; open south door.",
	"Investigate the statue twice; open east door.",
	"Take the <span class='key'>Scythe key</span>.",
	"Return to the hallway: west, north, east, north doors.",
	"Return to the upstairs lobby: west, south, east doors.",
	"Unlock east door with the <span class='key'>Scythe key</span>.",
	
	"<br><b>Skull door</b>",
	"Open south-eastern door (<span class='safe'>safe room</span>).",
	"Investigate the shrine for the <span class='item'>Grand piano key</span> and <span class='key'>Skull key</span>. Leave.",
	"Peek through the west door after a scream. Click Go Back.",
	"Unbolt then open north-eastern door.",
	"Open west-northern then west doors.",
	"Descend the stairs.",
	"Open south-eastern door.",
	"<span class='purple'>The windows shatter. Open west door.</span>",
	"Return to the lobby: west door.",
	"<span class='purple'>Open west-southern door (<span class='safe'>safe room</span>).</span>",
	"Open north door.",
	"Unlock north door with the <span class='key'>Skull key</span>.",
	
	"<br><b>Cleaver door</b>",
	"Open east-southern door.",
	"Search Ormod's scribblings for a <span class='item'>Scroll fragment</span>. Leave.",
	"Open north, west doors.",
	"Play the piano.",
	"Open south hidden door.",
	"<span class='purple'>Search south-east skeleton for the seventh <span class='item'>Eye gem</span>. Leave.</span>",
	"Return to the hallway: east door.",
	"Open south-eastern door.",
	"Descend the stairs.",
	"Open west-northern door.",
	"Search the Butler for the <span class='key'>Cleaver key</span>. Leave.",
	"Unlock north-eastern door with the <span class='key'>Cleaver key</span>.",
	
	"<br><b>Snake & Doll doors</b>",
	"<b>Walk</b> to the south-eastern door while avoiding knives.",
	"You can run again. Open north-middle door.",
	"Search the Chest of drawers for a <span class='item'>Large pipette</span>. Leave.",
	"Open north-eastern door.",
	"Use pipette on pig to get <span class='item'>Large pipette of pig bile</span>. Leave.",
	"Open east door.",
	"Search the Furnace for <span class='item'>Human ashes</span>. Leave.",
	"Use the <span class='item'>Pipette of pig bile</span> and <span class='item'>Human ashes</span> on the cauldron.",
	"Use the <span class='item'>Large pipette</span> on the cauldron to get <span class='item'>Alkaline concoction</span>.",
	"Use the <span class='item'>Alkaline concoction</span> on south door, then open it.",
	"Open west door.",
	"Investigate the Frozen servant for the <span class='key'>Doll key</span>.",
	"Return to the hallway: east door.",
	"Open east-northern door.",
	"Take the <span class='key'>Snake key</span> from the key hooks next to the ladder.",
	"Return to the lobby: Climb the ladder with the <span class='key'>Snake key</span>.",
	"<span class='purple'>Use the stairs, then open west door.</span>",
	"Unlock west door with the <span class='key'>Doll key</span>.",
	
	"<br><b>Tusks door & Statue door again</b>",
	"Ascend the stairs.",
	"Take the <span class='key'>Tusks key</span>.",
	"Descend the stairs. Leave.",
	"Open north then east door.",
	"Unlock south-eastern door with the <span class='key'>Tusks key</span>.",
	"Investigate the Bust and enter the Trap door.",
	"Search the Thief for the eighth <span class='item'>Eye gem</span>.",
	"Climb the Ladder. Leave.",
	"Open south-western door.",
	
	"<br><b>Noose door</b>",
	"Return to the fourth statue: west, south, east doors.",
	"Investigate the statue twice; open hidden east door (<span class='safe'>safe room</span>).",
	"Take the <span class='item'>Mother's hairbrush</span> from the shrine.",
	"Return to the hallway: west, west, north, east, north doors.",
	"Open west, south, west doors.",
	"Ascend the stairs.",
	"Talk to the spirit. Finish the dialogue for the <span class='key'>Noose key</span>.",
	"<b>Warning: A monster now chases you through most corridors.</b>",
	"Return to the upstairs lobby: east, east doors.",
	"<span class='purple'>Unbolt then open north door.</span>",
	"Open east door.",
	"<b>Quickly</b> unlock south door with the <span class='key'>Noose key</span>.",
	
	"<br><b>Basement</b>",
	"Open and climb into the cupboard. (The basement is safe)",
	"Follow the path. Peek through the peephole along the north wall.",
	"Unbolt then open west door.",
	"Open east-northern door.",
	"Descend the stairs.",
	"Open east door.",
	"Descend the stairs.",
	"Move all but the north Statue, then stand on the middle plate.",
	"Descend three flights of stairs.",
	"Climb down the rope (<span class='safe'>safe room</span>).",
	
	"<br><b>Chains door & Returning upstairs</b>",
	"Open east door.",
	"Search the Reception desk for <span class='item'>Nabor's notes</span> and the <span class='key'>Chains key</span>.",
	"Open north, east doors.",
	"Unlock east door with the <span class='key'>Chains key</span>.",
	"Open east, east doors.",
	"Take the <span class='key'>Dagger key</span> in the southwest cell.",
	"Return to the safe room: west, west, west, west, south, west doors.",
	"Climb the rope.",
	"Ascend six flights of stairs.",
	
	"<br><b>Dagger door & Finale<br>Warning: The monster chases you after you leave this room.</b>",
	"Open north, south-western, south, south doors (<span class='safe'>safe room</span>).",
	"Return to the lobby: east door.",
	"<span class='purple'>Climb the stairs. Move the Servant and open east door.</span>",
	"<b>Quickly</b> unlock south-western door with the <span class='key'>Dagger key</span>.",
	"Search Ingram's rantings for the last <span class='item'>Scroll fragment</span>.",
	"Combine the <span class='item'>Fragments</span> and <span class='item'>Notes</span> to make the <span class='item'>Break curse scroll</span>.",
	"Return to the hallway: north door.",
	"<b>Quickly</b> run east, use the <span class='item'>Break curse scroll</span> on the monster.",
	"Finish the dialogue.",
];

for (let step of steps) {
	let stepLine = document.createElement("div");
	stepLine.innerHTML = step;
	stepLine.addEventListener("mousedown", e => { if (e.buttons == 1) {
		stepLine.classList.toggle("done");
	}});
	
	document.querySelector("#step-list").appendChild(stepLine);
}

if (window.alt1 && alt1.versionint > 1001000) { alt1.identifyAppUrl("appconfig.json"); }
